### ISSUE TITLE
Original Protobuf file

### ISSUE THREAD

**Issue by zamazan4ik** [neguse/gomelift#1]
Hi! Thanks for the library!

Now I'm trying to build the same for the Rust language. I see that in `gomelift` you already have generated Protobuf file. Can you share please the original `sdk.proto` file too? It will be much easier to generate Protobuf bindings for other libraries.

Thanks in advance!

**Comment by neguse** [comment]
@ZaMaZaN4iK 
Hi! Thank you for your interest, your implementation in Rust is very exciting and interesting.

When I implemented this library, I used this protocol file.
https://github.com/dplusic/GameLift-Server-Protobuf
This was reversely created from the official AWS Server SDK.

I think that AWS should provide an official sdk.proto file. Otherwise, it will be difficult for SDK users to update the protocol buffers library.
There have been several similar feedbacks in the official forum, but no progress seems to be made.
https://forums.awsgametech.com/t/problems-using-the-gamelift-sdk-with-custom-protobuf-version/7557
https://forums.awsgametech.com/t/can-you-please-distribute-sdk-proto-instead-of-sdk-pb-h/2347

I hope this information is of some help.
Thanks!
